# Generated by Django 5.2.3 on 2025-08-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlers_main',
            name='content',
            field=models.TextField(max_length=50),
        ),
    ]
