# Generated by Django 5.2.3 on 2025-07-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawlers_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='crawlers_osusume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_title', models.CharField(max_length=50)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
