# Generated by Django 5.2.3 on 2025-07-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_crawlers_main_crawlers_osusume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlers_main',
            name='city',
        ),
        migrations.AddField(
            model_name='crawlers_main',
            name='img',
            field=models.CharField(default='空', max_length=50),
        ),
        migrations.AddField(
            model_name='crawlers_main',
            name='parent_title',
            field=models.CharField(default='空', max_length=50),
        ),
    ]
