# Generated by Django 5.2.3 on 2025-07-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_crawlers_main_city_crawlers_main_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlers_main',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
