# Generated by Django 5.2.3 on 2025-08-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_crawlers_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlers_main',
            name='heading',
            field=models.TextField(),
        ),
    ]
